std = "roblox"

[rules]
almost_swapped = "warn"
divide_by_zero = "deny"
empty_if = "warn"
global_usage = "warn"
if_same_then_else = "warn"
ifs_same_cond = "warn"
multiple_statements = "deny"
parenthese_conditions = "allow"
roblox_incorrect_color3_new_bounds = "deny"
roblox_incorrect_roact_usage = "deny"
shadowing = "warn"
incorrect_standard_library_use = "deny"
suspicious_reverse_loop = "deny"
type_check_inside_call = "deny"
unbalanced_assignments = "deny"
undefined_variable = "warn"
unscoped_variables = "warn"
unused_variable = "warn"